# Generated by Django 4.1.dev20211224190413 on 2021-12-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tousuid', models.CharField(max_length=10, null=True, verbose_name='投诉ID')),
                ('lyqd', models.CharField(blank=True, max_length=20, null=True, verbose_name='来源渠道')),
                ('jbhm', models.CharField(blank=True, max_length=12, null=True, verbose_name='举报号码')),
                ('bjbhm', models.CharField(blank=True, max_length=12, null=True, verbose_name='被举报号码')),
                ('jbhmyys', models.CharField(blank=True, max_length=12, null=True, verbose_name='举报号码运营商')),
                ('jbhmgssf', models.CharField(blank=True, max_length=12, null=True, verbose_name='举报号码归属省份')),
                ('jbhmgscs', models.CharField(blank=True, max_length=12, null=True, verbose_name='举报号码归属城市')),
                ('bjbhmgssf', models.CharField(blank=True, max_length=12, null=True, verbose_name='被举报号码归属省份')),
                ('bjbhmgscs', models.CharField(blank=True, max_length=12, null=True, verbose_name='被报号码归属城市')),
                ('jb_date', models.DateTimeField(blank=True, null=True, verbose_name='举报时间')),
                ('rk_date', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('ld_date', models.DateTimeField(blank=True, null=True, verbose_name='来电时间')),
                ('bllx', models.CharField(blank=True, max_length=20, null=True, verbose_name='不良类型')),
                ('thsc', models.CharField(blank=True, max_length=20, null=True, verbose_name='通话时长')),
                ('bjbhmlx', models.CharField(blank=True, max_length=12, null=True, verbose_name='被举报号码类型')),
                ('jbnr', models.TextField(blank=True, max_length=400, null=True, verbose_name='举报内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='投诉添加时间')),
                ('who', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户是谁')),
                ('is_cszl', models.BooleanField(blank=True, default=False, null=True, verbose_name='资料是否齐全')),
                ('is_tjyd', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否提交给移动')),
                ('csjg', models.CharField(blank=True, max_length=40, null=True, verbose_name='催收机构名称')),
                ('csms', models.TextField(blank=True, max_length=200, null=True, verbose_name='催收描述')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='资料更新时间')),
            ],
        ),
    ]
