# Generated by Django 4.1.dev20211224190413 on 2021-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='thsc',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='通话时长'),
        ),
    ]
