# Generated by Django 4.1.dev20211224190413 on 2021-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0002_alter_complaint_thsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='jbnr',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='举报内容'),
        ),
    ]
