# Generated by Django 4.1.dev20211224190413 on 2021-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0004_complaint_bcsr_complaint_is_br_complaint_yqje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_br',
            field=models.BooleanField(default=True, verbose_name='投诉号码是否是本人'),
        ),
    ]
