# Generated by Django 4.1.dev20211224190413 on 2021-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0005_alter_complaint_is_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cszl_mp3',
            field=models.FileField(null=True, upload_to='', verbose_name='通话录音'),
        ),
    ]
