# Generated by Django 4.1.dev20211224190413 on 2021-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0006_complaint_cszl_mp3'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cszl_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='借款资料'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cszl_mp3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='通话录音'),
        ),
    ]
