# Generated by Django 4.0 on 2021-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0010_alter_complaint_cszl_img_alter_complaint_cszl_mp3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tousuid',
            field=models.CharField(default=0, max_length=10, primary_key='tousuid', serialize=False, verbose_name='投诉ID'),
            preserve_default=False,
        ),
    ]
