# Generated by Django 4.0 on 2021-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0011_remove_complaint_id_alter_complaint_tousuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tousuid',
            field=models.CharField(default='', max_length=10, primary_key='tousuid', serialize=False, verbose_name='投诉ID'),
        ),
    ]
