# Generated by Django 4.0 on 2022-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0012_alter_complaint_tousuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cszl_img',
        ),
        migrations.AddField(
            model_name='complaint',
            name='cszl_img1',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/images/', verbose_name='借款资料1'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='cszl_img2',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/images/', verbose_name='借款资料2'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='cszl_img3',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/images/', verbose_name='借款资料3'),
        ),
    ]
