# Generated by Django 4.0 on 2022-01-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0013_remove_complaint_cszl_img_complaint_cszl_img1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name_plural': '1 - 投诉管理'},
        ),
        migrations.CreateModel(
            name='DownloadComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tousuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaintcms.complaint', verbose_name='投诉ID')),
            ],
            options={
                'verbose_name_plural': '2 - 下载管理',
            },
        ),
    ]
