# Generated by Django 4.0 on 2022-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintcms', '0014_alter_complaint_options_downloadcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadcomplaint',
            name='img1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='资料1'),
        ),
        migrations.AddField(
            model_name='downloadcomplaint',
            name='img2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='资料2'),
        ),
        migrations.AddField(
            model_name='downloadcomplaint',
            name='img3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='资料3'),
        ),
        migrations.AddField(
            model_name='downloadcomplaint',
            name='mp3_wav',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='录音'),
        ),
    ]
