# Generated by Django 4.0 on 2022-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kehu',
            fields=[
                ('zhanghao', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('zhanghu', models.CharField(max_length=40)),
                ('balance', models.FloatField(max_length=10)),
            ],
        ),
    ]
