# Generated by Django 4.0 on 2022-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehu',
            name='balance',
            field=models.FloatField(max_length=10, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='kehu',
            name='zhanghao',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='kehu',
            name='zhanghu',
            field=models.CharField(max_length=40, verbose_name='账户'),
        ),
    ]
