# Generated by Django 4.0 on 2022-01-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_kehu_balance_alter_kehu_zhanghao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huasu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='话术名称')),
                ('content', models.TextField(max_length=800, verbose_name='话术内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否审核通过')),
            ],
            options={
                'verbose_name_plural': '话术管理',
            },
        ),
        migrations.AlterModelOptions(
            name='kehu',
            options={'verbose_name_plural': '账号信息'},
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网关名称')),
                ('rate', models.CharField(max_length=20, verbose_name='费率')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.kehu')),
            ],
            options={
                'verbose_name_plural': '网关管理',
            },
        ),
    ]
