# Generated by Django 4.0 on 2022-01-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_huasu_alter_kehu_options_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehu',
            name='company_doc',
            field=models.FileField(blank=True, null=True, upload_to='crms/files/', verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='kehu',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='crms/files/', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='kehu',
            name='other_doc',
            field=models.FileField(blank=True, null=True, upload_to='crms/files/', verbose_name='补充附件'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.kehu', verbose_name='网关前缀'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(auto_now=True, null=True, verbose_name='缴费时间')),
                ('before_charge', models.FloatField(max_length=20, verbose_name='缴费前余额')),
                ('after_charge', models.FloatField(max_length=20, verbose_name='缴费后余额')),
                ('charge_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.kehu', verbose_name='缴费金额')),
            ],
            options={
                'verbose_name_plural': '缴费记录',
            },
        ),
    ]
