# Generated by Django 4.0 on 2022-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_kehu_zhanghu_alter_gateway_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanghu',
            name='tel_phone',
            field=models.CharField(default='', max_length=40, verbose_name='联系方式'),
        ),
    ]
